import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from "next-auth/next"
import NextAuthSessionProvider from './providers/sessionProvider'
import { authOptions } from './utils/authOptions'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider session={session}>
          { children }
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
